In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [32]:
df=pd.read_csv(r"Task1\data\penguins.csv")

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Species         150 non-null    str
 1   CulmenLength    148 non-null    float64
 2   CulmenDepth     148 non-null    float64
 3   FlipperLength   148 non-null    float64
 4   OriginLocation  150 non-null    str
 5   BodyMass        148 non-null    float64
dtypes: float64(4), str(2)
memory usage: 7.2 KB

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
X = df.drop(columns=["Species"])
y = df["Species"]

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
df.describe()

       CulmenLength  CulmenDepth  FlipperLength     BodyMass
count    148.000000   148.000000     148.000000   148.000000
mean      45.089865    17.377703     199.277027  4186.486486
std        5.385578     2.072129      14.160797   817.476925
min       34.100000    13.100000     172.000000  2700.000000
25%       40.500000    15.700000     187.750000  3550.000000
50%       46.100000    17.800000     196.000000  3950.000000
75%       49.350000    18.900000     212.250000  4681.250000
max       59.600000    21.500000     230.000000  6300.000000

In [38]:
X_train = pd.get_dummies(X_train, columns=["OriginLocation"],dtype=int)
X_test = pd.get_dummies(X_test, columns=["OriginLocation"],dtype=int)

In [39]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [40]:
num_cols = ["CulmenLength", "CulmenDepth",
            "FlipperLength", "BodyMass"]

In [41]:
X_train.isnull().sum()
X_test.isnull().sum()

CulmenLength                1
CulmenDepth                 1
FlipperLength               1
BodyMass                    1
OriginLocation_Biscoe       0
OriginLocation_Dream        0
OriginLocation_Torgersen    0
dtype: int64

In [42]:
med=X_train[num_cols].median()

X_train[num_cols] = X_train[num_cols].fillna(med)
X_test[num_cols] = X_test[num_cols].fillna(med)

In [43]:
X_train.isnull().sum()
X_test.isnull().sum()

CulmenLength                0
CulmenDepth                 0
FlipperLength               0
BodyMass                    0
OriginLocation_Biscoe       0
OriginLocation_Dream        0
OriginLocation_Torgersen    0
dtype: int64

In [44]:
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [47]:
X_train.head()

,CulmenLength,CulmenDepth,FlipperLength,BodyMass,OriginLocation_Biscoe,OriginLocation_Dream,OriginLocation_Torgersen
22,-1.694113,0.864183,-0.771963,-0.463271,1,0,0
15,-1.567428,0.178064,-1.057435,-0.585856,0,0,1
65,0.948179,1.060217,0.084452,-0.156807,0,1,0
11,-1.350253,-0.066978,-1.414275,-0.585856,0,0,1
42,-1.676015,0.521124,-0.986067,-1.321369,0,1,0

In [48]:
X_test.head()

,CulmenLength,CulmenDepth,FlipperLength,BodyMass,OriginLocation_Biscoe,OriginLocation_Dream,OriginLocation_Torgersen
73,0.966277,0.962200,-0.486492,-0.463271,0,1,0
18,-1.965582,0.472115,-1.128803,-1.045552,0,0,1
118,0.169969,-1.439216,0.655396,0.762584,1,0,0
78,0.206165,0.178064,-0.629228,-0.585856,0,1,0
76,0.948179,0.472115,0.013084,-0.953613,0,1,0